[pytest]
testpaths = tests
pythonpath = src
filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
    ignore:Warning only once for all operators,.*other operators may also be overridden.:UserWarning
markers =
    median: Median operator tests
