[pytest]
testpaths = tests
pythonpath = src
filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
    ignore:warmup, rep, and use_cuda_graph parameters are deprecated:DeprecationWarning
    ignore:Warning only once for all operators.*:UserWarning
