[pytest]
testpaths = tests
pythonpath = src
filterwarnings = ignore::pytest.PytestUnknownMarkWarning
markers =
    upsample_nearest2d: tests for aten::upsample_nearest2d
    upsample_nearest2d_backward: tests for aten::upsample_nearest2d_backward
