# Auto-generated by FlagGems AI Optimizer
# Operator: silu

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry


@triton.autotune(
    configs=[
        triton.Config({"BLOCK_SIZE": 128}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 256}, num_warps=2),
        triton.Config({"BLOCK_SIZE": 256}, num_warps=4),
    ],
    key=["BLOCK_SIZE"],
)
@triton.jit
def silu_kernel(x_ptr, output_ptr, n_elements, block_size: tl.constexpr):
    pid = tl.program_id(axis=0)
    idx = tl.global_thread_idx()

    if idx < n_elements:
        x = tl.load(x_ptr + idx * 2)

        if x.dtype == tl.float16:
            sigmoid_x = 1 / (1 + tl.exp(-x))
            output = x * sigmoid_x
        elif x.dtype == tl.bfloat16:
            sigmoid_x = 1 / (1 + tl.exp(-x))
            output = x * sigmoid_x
        elif x.dtype == tl.float32:
            sigmoid_x = 1 / (1 + tl.exp(-x))
            output = x * sigmoid_x

        tl.store(output_ptr + idx * 2, output)


import torch


@libentry()
def silu_wrapper(x: torch.Tensor) -> torch.Tensor:
    output = torch.empty_like(x)
    n_elements = x.numel()
    block_size = 256
    silu_kernel[meta](x.data_ptr(), output.data_ptr(), n_elements, block_size)
    return output
